GiftForGood/website

- .prettierrc.json
- README.md
- package-lock.json
- package.json
- pages/index.js
For more info on the options that Prettier provides, can look here: [Prettier Options](https://prettier.io/docs/en/options.html).
> Add prettier code formatter

- .env.sample
- README.md
- config/server/parse-env.sh
- next.config.js
- package-lock.json
- package.json
In this PR,
- Added script to parse environment variables 
- Added `next.config.js` for environment variables 
- Updated `README.md` to guide how to add environment variables
> Environments

- package-lock.json
- package.json
To use our images/icons stored in Cloudinary, can do the following:
```js
import { CloudinaryContext, Image } from 'cloudinary-react';
<CloudinaryContext cloudName="giftforgood"> // note that giftforgood is our cloud name
<div>
<Image publicId="image-name" width="50" /> // match with image name in cloudinary
</div>
<Image publicId="image-name" width="0.5" />
</CloudinaryContext>
```
We are utilising the free tier, the following link shows the limits/perks of free tier: https://cloudinary.com/pricing
> Add Cloudinary dependencies

- next.config.js
- package-lock.json
- package.json
- utils/firebase/index.js
In this PR: 
- Installed `firebase` and `firebase-admin`
- Initialize firebase app
- Add firebase config to env
> Setup Firebase

- .prettierignore
- .prettierrc.json
- next.config.js
- package.json
- pages/index.js
- utils/api/auth.js
- utils/api/categories.js
- utils/api/constants.js
- utils/api/donations.js
- utils/api/index.js
- utils/api/npoOrganizations.js
- utils/api/report.js
- utils/api/reports.js
- utils/api/reviews.js
- utils/api/users.js
- utils/api/wishes.js
- utils/firebase/index.js
In this PR:
- Added AuthAPI skeleton 
- Added CategoriesAPI skeleton
- Added WishesAPI skeleton
- Added DonationsAPI skeleton
- Added UsersAPI skeleton
- Added ReportsAPI skeleton
- Added ReviewsAPI skeleton
- Added NPOOrganizationsAPI skeleton
- Update Prettier to check all `.js` files
- Added `.prettierignore`
> API Skeleton

- utils/api/categories.js
In this PR:
- Added CategoriesAPI implementation
> CategoriesAPI Implementation

- utils/api/auth.js
In this PR: 
- Added APIAuth implementation for donor
> APIAuth Implementation - Donor

- utils/api/auth.js
- utils/api/error/authError.js
- utils/constants/siteUrl.js
In this PR: 
- Remove silent login
- Update `sendVerificationEmail()`
- Update error messages
> Fix donor auth error

- utils/api/npoOrganizations.js
In this PR: 
- Added implementation for NPOOrganizationAPI
> NPOOrganizationsAPI Implementation

- utils/api/auth.js
- utils/constants/npoRegisteredRegistrar.js
- utils/firebase/index.js
In this PR: 
- Add AuthAPI implementation for NPO
> APIAuth Implementation - NPO

- utils/admin-firebase/index.js
Reverts GiftForGood/website#103
> Revert "Fix authentication network error"

- package-lock.json
- package.json
As noted in https://github.com/firebase/firebase-js-sdk/issues/2923, I am too facing this bug in Chrome. This PR downgrades to `7.14.1` and it works on my Chrome.
> Downgrade firebase to 7.14.1 due to bug

- src/components/card/WishCard.js
- src/components/category/pages/WishesViewCategoryPage.js
Chrome console is giving errors for non unique keys, let's fix it.
> Fix error for non unique keys for Tags component

- pages/wishes/[wishId].js
- src/components/card/GroupWishCard.js
- src/components/card/WishCard.js
- src/components/category/pages/ViewAllWishesPage.js
- src/components/category/pages/WishesViewCategoryPage.js
- src/components/home/modules/TopWishes.js
- src/components/postDetails/BreadcrumbsPanel.js
- src/components/postDetails/PostDetailsHeader.js
- src/components/postDetails/UserInfoCard.js
- src/components/wishDetail/modules/Map.js
- src/components/wishDetail/modules/WishInformation.js
- src/components/wishDetail/pages/WishPage.js
In this PR, 
- Added breadcrumbs for desktop version 
- Fixed check profile endpoint `profile/userId`
- Fixed content padding inside info window google maps
- Changed `og:image` to our logo in meta property
> Some updates on wish-details page 

- pages/wishes/[wishId].js
- utils/constants/imagePaths.js
In this PR,
Fix meta property og:image, as it doesnt support `svg`
> fix share og:image share for logo

- package-lock.json
- package.json
- utils/api/error/userError.js
- utils/api/users.js
In this PR: 
- Add implementation for UsersAPI
- Install `uuid` package
What needs to be done:
- Will be adding the cloud functions to update the relevant collections documents that contain the user info.
> UsersAPI Implementation

- pages/wishes/create.js
In this PR,
- Fixed error `http 500` when u are not logged in and tries to access the page
> Fix http 500 for create-wish page

- src/components/buttons/CallToActionButton.js
- src/components/session/modules/Verified.js
In this PR,
- Checked for user type for the `Verified` component. 
- For `npo` to use a component --> `emailVerified` and `adminVerified` 
- For `donor` to use a component --> `emailVerified`
> Check for user type within Verified component

- src/components/buttons/CallToActionButton.js
In this PR,
- Link up the CTA button to correct pages 
- donor --> `donations/create`
- npo --> `wishes/create`
> Link up post button

- utils/api/donations.js
In this PR:
- Refractor error handling
- Change post status to use constant
- Update categories in donations to store only `id` and `name`
- Abstract some functions to use common functions
> DonationsAPI Fixes

- pages/donations/category/[categoryId].js
- pages/wishes/category/[categoryId].js
- utils/api/categories.js
In this PR: 
- Filter all categories by `shouldShow`
- Minor changes to `getById` and `getByName`
> CategoriesAPI Fixes

- src/components/login/modules/LoginDonor.js
- src/components/login/modules/LoginNpo.js
- src/components/register/modules/RegisterDonor.js
- src/components/register/modules/RegisterNpoDetails.js
```
After register/login procedures, the loading animation stops 
and there is seconds of delay before routing to the home page.
Let's set the loading animation to continue until the page 
routes away.
```
> Let loading animation continue until page routes away

- src/components/createWish/modules/createWishPanel.js
- src/components/createWish/modules/livePreviewPanel.js
- src/components/inputfield/GooglePlacesAutoCompleteField.js
- src/components/navbar/modules/TopRightNavigation.js
- utils/api/time.js
- utils/constants/thirdPartyAPIUrl.js
- utils/hooks/useLocalStorage.js
In this PR,
- Add alert to inform user about 1 month wish life 
- Add expireAt field to tell user the exact date it will expire 
- Add google places auto complete field
> Update create wishes location auto complete

- pages/settings/profile.js
- src/components/settings-profile/donor/modules/DonorEditProfilePanel.js
- src/components/settings-profile/donor/pages/DonorSettingProfilePage.js
- utils/authentication/userType.js
> Add edit profile for donors

- src/components/card/DonationCard.js
- src/components/home/modules/TopDonations.js
Forgot to pass the valid period from the donation to the donation card.
> Add missing valid period field in donations home page

- src/components/wishDetail/modules/Map.js
- src/components/wishDetail/pages/WishPage.js
A preview of multiple markers (in future):
`http://localhost:3000/wishes/m2OWDc6AQekYuDnwtfvY?categoryId=&categoryName=All%20wishes`
> Fix map marker location in wish details page

- pages/donations.js
- pages/donations/category/[categoryId].js
- pages/donations/category/index.js
- pages/index.js
- pages/profile/[userId].js
- pages/wishes/category/[categoryId].js
- pages/wishes/category/index.js
- src/components/buttons/CallToActionButton.js
- src/components/navbar/modules/BottomNavigation.js
- src/components/navbar/modules/EmailVerificationNavigationBar.js
- src/components/navbar/modules/TopNavigationBar.js
- utils/constants/navbar.js
In this PR,
- Rebuilt navbar. Currently the `red` email verification bar is at the top followed by the normal navbar. 
- Added bottom CTA button with scrolling enabled for phone and tablet. 
Credit to @jinyingtan for helping me figure out CSS
> Rebuilt navbar

- src/components/card/DonationCard.js
- src/components/donationDetail/modules/ImagePanel.js
- utils/constants/colors.js
In this PR,
- Optimised image for `DonationCard` -> will load `500x500`
- Optimised image for `ImagePanel` -> will load `1000x1000`
Assumption made
- All images will have `default`, `500x500` and `1000x1000` size. 
Currently, some of the existing photos, do not have these sizes and there is no way to alter them. We can only purge the donations and re-populate them.
> Image optimization

- src/components/donationDetail/modules/DonationInformation.js
- src/components/donationDetail/pages/DonationPage.js
- src/components/postDetails/PostDetailsHeader.js
- src/components/wishDetail/modules/WishInformation.js
- src/components/wishDetail/pages/WishPage.js
Disable the chat button if:
- Logged in user is a `donor` and the post is a `donation` and the post is not created by the logged in user
- Logged in user is a `npo` and the post is a `wish` and the post is not created by the logged in user
> Disable chat button when post and user is of the same type

- pages/donations/create.js
- pages/donations/edit.js
- src/components/card/DonationCard.js
- src/components/createDonation/actions.js
- src/components/createDonation/modules/DragNDropInputField.js
- src/components/createDonation/modules/createDonationPanel.js
- src/components/createDonation/modules/livePreviewDonation.js
- src/components/createDonation/pages/createDonationPage.js
- src/components/createDonation/reducers.js
- utils/api/donations.js
- utils/api/time.js
In this PR,
- Added edit mode for donations
Waiting for @jinyingtan api fixes
> Edit donations

- utils/api/chats.js
- utils/api/common/user.js
In this PR: 
- Return chat and chat messages document in functions that create initial chat messages
- Fix getting of current user bug
> ChatsAPI Fixes

- utils/api/common/images.js
- utils/api/donations.js
- utils/constants/imageVariation.js
In this PR: 
- Change how image urls are stored
- Update create & update donation functions to reflect changes
> DonationsAPI: Update donations image urls format

- src/components/buttons/RedButton.js
- src/components/card/DonationCard.js
- src/components/createDonation/modules/createDonationPanel.js
- src/components/donationDetail/modules/ImagePanel.js
In this PR,
- Reflecting the schema changes 
- Updated `DonationCard.js`, `ImagePanel.js` and `createDonationPanel.js`
> Fix donations images update

- src/components/navbar/modules/TopLeftNavigation.js
In this PR,
- Prefetched `donations home page`, `wishes home page`
Prefetch only works in production environment, so if u wanna test it, make sure you `build` and `start`. Open your network tab in chrome and look for the particular js file
> Prefetch pages

- src/components/card/CardHeader.js
- src/components/card/GroupWishCard.js
- src/components/navbar/modules/TopRightNavigation.js
- src/components/postDetails/PostDetailsHeader.js
- src/components/postDetails/UserInfoCard.js
- src/components/profile/modules/ProfileDetails.js
- src/components/settings-profile/donor/modules/DonorEditProfilePanel.js
- src/components/settings-profile/npo/modules/NpoEditProfilePanel.js
In this PR,
- Updated profile images everywhere to use new profileImageUrl schema
All are updated except for the `chat`
> Update profile picture new schema

- pages/api/mrt.js
- public/assets/mrt-list.json
- src/components/createDonation/modules/createDonationPanel.js
- src/components/inputfield/MrtDropdownField.js
In this PR,
- Update create donations with MRT list
- Create MRT api using `nextjs`
- MRT list consist of `NSL`, `EWL`, `NEL`, `CCL`, `DTL`, `Seng Kang LRT`, `Bukit Panjang LRT`, `Punggol LRT`
> Update create donation to use mrt list

- utils/api/auth.js
In this PR: 
- Remove registered registrar & proof image
- Add status, admin, appliedDateTime & lastUpdatedDateTime field to npoVerifications
> AuthAPI: Update npo verifications

- src/components/navbar/modules/TopRightNavigation.js
- src/components/register/modules/RegisterNpoDetails.js
- src/components/register/modules/RegisterNpoOrganization.js
In this PR,
- Update NPO register page to remove `Proof image` and `registrar` 
- Fix a bug for nav bar with missing navbar image
> npo register removal proof

- src/components/category/modules/DonationsHitWrapper.js
In this PR,
- Add locations back to donations card
> Add locations

- pages/chat/index.js
- Add check if the user is email verified. Because even though button is disabled, the url can be manipulated to go to the create new chat page
- Add check if the user is creating chat for the same type of post (i.e. donor -> donation, npo -> wishes). Because even though button is disabled, the url can be manipulated to go to the create new chat page
> Add checks in chat

- src/components/modal/ReportPostModal.js
> Reword report post's reason placeholder

- src/components/chat/modules/ChatDialog.js
- src/components/chat/modules/ChatDialogUserRow.js
- src/components/donationDetail/modules/DonationInformation.js
- src/components/donationDetail/pages/DonationPage.js
- src/components/postDetails/PostDetailsHeader.js
- src/components/postDetails/UserInfoCard.js
- src/components/profile/modules/ProfileDetails.js
- src/components/profile/modules/ProfileHeaderBar.js
- src/components/profile/modules/ProfilePanel.js
- src/components/profile/pages/DonorProfilePage.js
- src/components/profile/pages/NpoProfilePage.js
- src/components/wishDetail/pages/WishPage.js
Removed usage of reviews and ratings in:
- Review panel in Donor profile and NPO profile
- ChatDialogUserRow
- ProfileHeader in post details page
While retaining the review/rating components in case we need to re-use it in the future
> Remove usage of reviews and ratings

- src/components/register/modules/RegisterNpoOrganization.js
In this PR,
- updated the labels of the input field to be clearer
> Update labels of input field

- src/components/inputfield/MrtDropdownField.js
In this PR,
- MRT list will auto close after selecting
> Fix autoclose mrt list after selecting

- src/components/createDonation/modules/createDonationPanel.js
- src/components/createWish/modules/createWishPanel.js
In this PR,
- Fixed on mobile and desktop to see selected category 
- Can unselect/select from the dropdown list as well
> Fix can see checkbox when selecting category

- utils/api/auth.js
Add error message when tries to login as a donor with the email and password of a NPO, vice versa
> AuthAPI: Fix login bug

- utils/api/auth.js
- utils/constants/notification.js
Resolves: #225 
Add default notification to npos and donors with this default notification
```
notifications: {
dailyEmailForChat: -1
weeklyEmailForChat: {
hour: 9
day: 1
}
```
> AuthAPI: Add notification data to npos and donors

- src/components/card/BumpableWishCard.js
- src/components/card/CardHeader.js
- src/components/card/DonationCard.js
- src/components/card/GroupWishCard.js
- src/components/card/WishCard.js
- src/components/category/modules/DonationsHitWrapper.js
- src/components/category/modules/WishesHitWrapper.js
- src/components/chat/modules/ChatDialogUserRow.js
- src/components/createDonation/modules/livePreviewDonation.js
- src/components/home/modules/TopDonations.js
- src/components/home/modules/TopWishes.js
- src/components/postDetails/PostDetailsHeader.js
- src/components/profile/modules/PastDonationsPanel.js
- src/components/profile/modules/PastWishesPanel.js
Fixes #256
Fixes #259 
Add profile page links to
- all avatar details in cards
- post details page's avatar details
- chat page avatar details
> Add profile page links to all avatar details

- src/components/profile/modules/ProfileHeaderBar.js
> Reword profile panel header

- src/components/card/DonationCard.js
- src/components/card/GroupWishCard.js
- src/components/card/WishCard.js
- src/components/donationDetail/modules/DonationInformation.js
- src/components/wishDetail/modules/WishInformation.js
> Allow multiline description for posts

- src/components/chat/modules/ChatDialogMessages.js
- src/components/chat/modules/ChatDialogViewPostRow.js
> Remove delivery cost message in see post row

- src/components/modal/ConfirmCompletionModal.js
> Reword confirm completion message

- src/components/navbar/modules/TopLeftNavigation.js
> Show wishes and donations button in navbar are clickable

- src/components/calendar/modules/Calendar.js
- src/components/calendar/modules/CalendarModal.js
> Make select delivery dates requirement more noticeable

- utils/api/categories.js
> Sort categories in alphabetical order

- src/components/register/modules/PasswordStrength.js
- src/components/register/modules/RegisterDonor.js
- src/components/register/modules/RegisterNpoDetails.js
- utils/constants/colors.js
In this PR,
- Added a `PasswordStrength` component as per figma design
- Added a `tick` when password strength is met
Fixes #267
> Add password strength indicator

- pages/api/silentLogin.js
In this PR,
- Provided a potential fix for silent login bug that causes `null`
My guess what went wrong: 
1) After the npo register, the cloud function isn't fired off yet
2) Thus `decodedClaims.donor is false` and `currentUser.customClaims` returns an empty object. So when i try to get `currentUser.customClaims.donor` is returns undefined. In production, undefined might cause an error. 
Here's a SS for the bug that i managed to capture in the server:
> Potential fix for silent login bug

- src/components/register/modules/RegisterNpoDetails.js
- src/components/register/modules/RegisterNpoOrganization.js
- utils/api/auth.js
> Remove registration date for npo registration

- src/components/profile/modules/CompletedDonationsPanel.js
- src/components/profile/modules/CompletedWishesPanel.js
- src/components/profile/modules/ProfileHeaderBar.js
- src/components/profile/pages/DonorProfilePage.js
- src/components/profile/pages/NpoProfilePage.js
- utils/api/donations.js
- utils/api/wishes.js
Fixes #265 
In this PR: 
- Added Completed Wishes/Donations API 
- Added Completed Donations Panel in NPO Profile Page
- Added Completed Wishes Panel in Donor Profile Page
> Completed Wishes/Donations

- src/components/category/pages/ViewAllWishesPage.js
- src/components/category/pages/WishesViewCategoryPage.js
- utils/algolia/filteringRules.js
In this PR,
- Add filtering of expired wishes
> Filter expired wishes

- src/components/chat/modules/ChatImageUpload.js
- src/components/createDonation/modules/DragNDropInputField.js
- src/components/settings-profile/donor/modules/DonorEditProfilePanel.js
- src/components/settings-profile/npo/modules/NpoEditProfilePanel.js
- utils/constants/files.js
Fixes #296 
Impose at:
- create donation
- edit npo profile
- edit donor profile
Refactor to use constant for MAXIMUM_FILE_SIZE_LIMIT
> Impose 25mb upload limit

- utils/api/auth.js
In this PR: 
- Add `unreadChatNotificationsCount` & `unreadNotificationsCount` to `donor` and `npo`
> AuthAPI: Add 2 notification fields

- utils/constants/closePostReasons.js
> Add close wish reasons

- src/components/home/modules/BannerCarousel.js
- utils/api/banners.js
In this PR:
- Update main banner api
- Add side banner api
> Add side banner api

- pages/delivery-partners.js
- src/components/deliveryPartners/modules/DeliveryPartnersContent.js
- src/components/deliveryPartners/pages/DeliveryPartnersPage.js
In this PR: 
- Add delivery partners page
Screenshot:
**Desktop View**
**Tablet View**
**Mobile View**
> Add delivery partners page

- contents/faq/faq.md
- src/components/chat/modules/ChatBubbleForCalendar.js
- src/components/contactUs/modules/ContactUsContent.js
- src/components/navbar/modules/TopNavigationBar.js
- utils/api/auth.js
- Add delivery partners to drawer
- Add in hello@giftforgood.io in contact us page
- Update FAQ
- Reword delivery message
- Add link to delivery partners in system generated message
- Reword auth error
> Minor changes based on comments

- utils/constants/npoPartners.js
In this PR, 
Added the following npos: 
- ADA
- Bethel 
- CPAS
- Habitat for Humanity
- Lion Befrienders
- Morning Star
- New Life
- SUN DAC 
- Viriya
> Add more npo partners

- src/components/card/DonationCard.js
- src/components/category/modules/DonationsHitWrapper.js
- src/components/createDonation/actions.js
- src/components/createDonation/initialState.js
- src/components/createDonation/modules/createDonationPanel.js
- src/components/createDonation/modules/livePreviewDonation.js
- src/components/createDonation/reducers.js
- src/components/createDonation/selectors.js
- src/components/home/modules/TopDonations.js
- src/components/profile/modules/CompletedDonationsPanel.js
- src/components/profile/modules/PastDonationsPanel.js
In this PR:
- Remove the `Locations:` for `Condition:` in donation card
> Update details in donation card

- src/components/category/modules/DonationsHitWrapper.js
- src/components/category/modules/WishesHitWrapper.js
In this PR,
- Fixed infinite loader 
Resources:
- https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/infinite-scroll/react/
- https://www.algolia.com/doc/api-reference/widgets/infinite-hits/react/#examples
> Fix infinite loader for algolia

- src/components/category/pages/DonationsViewCategoryPage.js
- src/components/category/pages/ViewAllDonationsPage.js
- src/components/category/pages/ViewAllWishesPage.js
- src/components/category/pages/WishesViewCategoryPage.js
- src/components/home/modules/TopDonations.js
- src/components/home/modules/TopWishes.js
- src/components/home/modules/algoliaHelpers.js
- src/components/search/modules/NavSearchBarDropdownList.js
- utils/algolia/index.js
In this PR,
- refactor searchClient into a file
> Refactor searchClient

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- package-lock.json
- package.json
- src/components/card/DonationCard.js
- src/components/card/WishCard.js
- src/components/category/modules/DonationsHitWrapper.js
- src/components/category/modules/WishesHitWrapper.js
- src/components/category/pages/DonationsViewCategoryPage.js
- src/components/category/pages/ViewAllDonationsPage.js
- src/components/category/pages/ViewAllWishesPage.js
- src/components/category/pages/WishesViewCategoryPage.js
- src/components/createDonation/modules/createDonationPanel.js
- src/components/createWish/modules/createWishPanel.js
- src/components/donationDetail/pages/DonationPage.js
- src/components/postDetails/PostDetailsHeader.js
- src/components/wishDetail/pages/WishPage.js
- utils/algolia/index.js
- utils/algolia/insights.js
In this PR,
- Collect different events 
New Libraries
- search-insight
> Personalization - Stage 1

- src/components/navbar/modules/MobileDrawer.js
- src/components/navbar/modules/TopLeftNavigation.js
> Add NPOs link to navbar and drawer

- src/components/aboutUs/modules/TeamDescription.js
- src/components/text/BlackText.js
- src/components/text/GreyText.js
> Modify about us page mobile view

- pages/search.js
- src/components/header/index.js
- src/components/search/modules/MobileSearchBar.js
- src/components/search/pages/SearchPage.js
In this PR,
- updated `/search` 
- updated `Header` component with new meta tag that prevents zooming on iOS Safari
> Update mobile search site

- src/components/category/modules/DonationsSortFilterPanel.js
- src/components/category/modules/WishesSortFilterPanel.js
In this PR,
- Redesigned mobile/tablet filter/sort UI for wishes/donations page
> Redesign filter/sort on mobile and tablet

- pages/wishes/create.js
- src/components/createWish/modules/createWishPanel.js
- src/components/postDetails/PostDetailsHeader.js
> Add duplicate wish feature

- src/components/footer/Footer.js
- src/components/navbar/modules/MobileDrawer.js
In this PR, 
Shift the footer content in the order as follows: 
About Us
Partners
Developer Student Club
Contact Us
FAQ
Privacy Policy
Terms and Conditions
Credits
> Shift footer content

- src/components/category/modules/WishesFilterBy.js
- src/components/category/modules/WishesSortFilterPanel.js
In this PR,
- Added Filtering by causes for wishes category page
> Add sector to filter

- utils/algolia/filteringRules.js
In this PR,
- Allow expired wishes on the site
> allow expired wishes

- utils/api/chats.js
This additional `createdDateTime` field is needed for analytics purposes
> Add createdDateTime field for new chats

- pages/_document.js
Reverts GiftForGood/website#396
> Revert "Update/gtag"

- src/components/home/pages/WishesHomePage.js
> Add padding for top wishes

- src/components/home/modules/TopDonations.js
- src/components/home/modules/TopWishes.js
- src/components/npos/modules/NposHitWrapper.js
In home page, donations home page and npo page
> Fix unique key errors

- src/components/inputfield/NpoOrganizationDropdownField.js
- src/components/register/modules/RegisterNpoOrganization.js
In this PR,
- Updated org search bar to use algolia in registration page,
- reason being now that we have a few thousands of org within our DB, using algolia makes more sense as compared to firebase. If we use firebase, there will be thousands of reads per page load for registration page.
> Use algolia for search organization in registration

- src/components/navbar/modules/TopRightNavigation.js
No matter at which page, after successfully logging in, it will go back to the previous page instead of home page
> Add redirect url after logging in

- src/components/wishDetail/modules/Map.js
Reference: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
> Disable clickable icons on google map

- pages/wishes/[wishId].js
- src/components/header/WishHeader.js
- utils/constants/imagePaths.js
In this PR,
- Add wish open graph image
> Add wish OpenGraph

- src/components/modal/RegisterLoginModal.js
- src/components/postDetails/PostDetailsHeader.js
When user is not logged in, clicking on chat button will open up the register login modal.
After registering it will redirect user back to the original page.
> Add register login modal

- pages/wishes/[wishId].js
- src/pages/wishDetail/components/Map/index.js
- src/pages/wishDetail/components/WishInformation/index.js
- src/pages/wishDetail/components/index.js
- src/pages/wishDetail/index.js
In this PR, 
- Refactored Wish Details page
> Refactor Wish Detail page

- package-lock.json
- package.json
Adding lint-staged will only run prettier on files that are changed instead of on all files.
> Add lint-staged to run prettier on changed files
