src/components/inputfield/index.js

iPhone IOS will not display box-shadow property properly, in this case: setting `-webkit-appearance: none` on the custom `Input` component will solve the issue. 
Reference: https://stackoverflow.com/questions/10757146/iphone-ios-will-not-display-box-shadow-properly
Screenshot from my iPhone safari. (Works for chrome as well)

Fix missing input field border

---

src/components/home/modules/TopWishes.js

The wish cards in home page contains broken links as they are still using wishesId. Let's modify them to use wishId instead.

Fix broken link in wish cards

---

pages/wishes/[wishId].js
pages/wishes/category/[categoryId].js
utils/api/auth.js

There are consecutive calls to async functions using the `await` keyword. By using `Promise.all`, we can execute them concurrently while not interrupting the flow of the function.

Use Promise.all for non-dependent async functions

---

utils/api/donations.js

Previously `update` function only allows updating of images where existing images will always come before new images. 
This fix allows the images to be updated in any order, following the order given by the images argument. Cover Image will always appear as the first image.

[DonationsAPI] update function to accept images in any order 

---

utils/api/donations.js

Previously, `fromDate` on the update donations could not accept the `fromDate` is before today's date  
This PR updates the validation from the `fromDate` to allow that from happening. 
- The current `fromDate` validation now allows `fromDate` to be before today's date 
- However, the updated `fromDate` needs to be the same day or after the previous `fromDate`

DonationsAPI: Update fromDate validation

---

src/components/chat/modules/ChatDialogInputRow.js

Iphone auto zooms into input fields when the font size is less than 16px. 
A potential solution to this is to set the font size as 16px, and use the css scale function to scale down the font size.  Solution is taken from: https://thingsthemselves.com/no-input-zoom-in-safari-on-iphone-the-pixel-perfect-way/
Can't test it out so not 100% sure if it'll resolve the issue

Potential fix for iphone auto zoom in 

---

pages/_app.js

It is seen that sometimes when the sentences are too long, the words does not break to the next line, causing the overflow to make the wrong alignment of the chat bubble. (Seen below)
Let's add the `word-break: break-word` property to prevent that.
After:

Fix overflow of chat message

---

src/components/chat/modules/ChatDialogMessages.js

Currently, it scrolls to the bottom of the chat messages if the incoming message is by the logged in user. This causes a scroll to bottom every time chat messages are updated, no matter it is older messages or new messages.
This pr allows only scroll to bottom of chat messages if it is a newly sent msg by logged in user.

Fix inconsistent scrolling to the bottom of chat messages

---

src/components/chat/modules/ChatBubbleForImage.js
src/components/chat/modules/ChatDialogMessages.js
src/components/chat/modules/ChatMessageSection.js

Currently, users are able to send images with height that exceeds the message container's height. This might not be the best UX as user needs to scroll to see the full image.
Additionally, this issue potentially causes another issue pointed out by @kohchihao, where sending a long image shows a white space within the messages container.

Prevent images in chat to be longer than chat dialog messages height

---

src/components/chat/modules/ListOfChats.js

Without the return key word, nothing is being returned to the `display` property

Add missing return key word in styled component

---

src/components/chat/modules/ChatBubbleForImage.js
src/components/chat/modules/ChatDialogMessages.js
src/components/chat/modules/ChatMessageSection.js

Within #192, the height of the viewport is calculated in JS using `window.innerHeight`. However, `window.innerHeight` takes into account of the keyboard and it creates several UI issues.
Let's use `100vh` to get the viewport height instead.

Remove use of window.innerHeight

---

src/components/chat/modules/ChatDialogMessages.js

Some mobile browsers do not support smooth scrolling in `scrollIntoView`, shown here: https://caniuse.com/#feat=scrollintoview

Remove smooth scrolling in scrollIntoView

---

package-lock.json
package.json
src/components/chat/modules/ChatDialog.js
src/components/chat/modules/ChatDialogInputRow.js
src/components/chat/modules/ChatDialogMessages.js
src/components/chat/modules/ListOfChats.js
src/components/profile/modules/PastDonationsPanel.js
src/components/profile/modules/PastWishesPanel.js
src/components/scroller/InfiniteScroller.js

Utilised `react-device-detect` to determine whether the device is mobile
Utilised `react-stay-scrolled` to (1) accurately scroll to the bottom of the messages and (2) make sure that the scroll position does not change when adding new chat messages. (needed because Safari does not support `overflow-anchor` property)
- Add scroll to bottom of chat dialog when mounted
- Uninstall `react-infinite-loader` (not being maintained actively), and overwrite it to fix the issue and use custom infinite loader. 
- Allow mobile to press `return/new line` button (which has the same keyCode as the enter key in desktops) to add new line instead of sending
- Prevent scroll position from changing when adding new chat messages.

Chat fixes

---

src/components/chat/modules/ChatMessageSection.js

Fixes the issue where in safari ios, not able to view the chat messages during initial load, but able to view the messages after a slight scroll.
Solution obtained from: https://css-tricks.com/forums/topic/safari-for-ios-z-index-ordering-bug-while-scrolling-a-page-with-a-fixed-element/

Fix white space in safari ios chat

---

src/components/chat/modules/ChatDialog.js
src/components/chat/modules/ChatDialogMessages.js
src/components/chat/pages/ChatPage.js
utils/hooks/useWindowDimensions.js

Currently, `100vh` is being used for the height of the viewport. However, `100vh` includes the height of the browser's bottom  panel. Hence, within the chat page, scrolling is needed to see the full page.
Let's create a hook that uses `window.innerHeight` to calculate the height of the viewport. `window.innerHeight` does not include the height of the browser's bottom panel.

Make height of chat page exactly fit into mobile

---

package-lock.json
package.json
src/components/chat/modules/ChatDialogMessages.js

Removing react-stay-scrolled package as it does not achieve what I initially thought it would achieve, i.e. maintain the scroll position when new items added within the scroller component.
Note: the `stayScrolled()` method **does not** maintain the scroll position, which is the main reason i wanted to use this package initially.

Remove react-stay-scrolled package

---

src/components/scroller/InfiniteScroller.js

Use isSafari to detect safari specific issue instead of checking if scrollTop is positive, to reduce side effects.

Fix bug with safari scroller in chat messages

---

src/components/card/BumpableWishCard.js
src/components/card/DonationCard.js
src/components/card/GroupWishCard.js
src/components/card/WishCard.js
src/components/donationDetail/modules/DonationInformation.js
src/components/wishDetail/modules/WishInformation.js

Fixes
- donation  and wish details:
Before
After
- donation cards:
Before
After
- bumpable wish card and wish cards:
Before
After
- group wish cards
Before
After

Add word break to all cards and post details

---

pages/chat/index.js
utils/api/chats.js

With the current approach, unsubscribing to chat messages gets the current user id to update some of the fields in chats. As highlighted by @jamessspanggg, when a user logged out on the chat page, the API will throw an error as current user will be null. 
To solve this issue, we will need to add `userId` to unsubscribe chat messages, so that we do not need to fetch the user. To ensure consistency in the API, I have to add `userId` to subscribing of chat messages as well.

ChatId: Add userId to subscribe and unsubscribe chat messages

---

src/components/chat/modules/ChatDialogInputRow.js

Fixes the issue where after sending the first text message, sending further messages shows a `chat already exists` error.
Fixes google docs issue 6

Fix chat already exists error after sending first text msg

---

src/components/inputfield/GooglePlacesAutoCompleteField.js

In this PR,
- when GooglePlaces input field is empty, it will call `onChanged` as well and clear the localStorage

Update with empty string

---

src/components/register/modules/RegisterNpoDetails.js

In this PR,
- Added a tooltip that appears when hover over the help text. 
- Appear as bottom modal with close button when on mobile 
- Currently the tooltip shows this text `Use your own name even though there might be multiple people sharing a single account.`. The reason is that we want them to use their own name regardless of the situation.
Fixes #272

Add tooltip for suggested name

---

src/components/createWish/context.js
src/components/createWish/index.js
src/components/createWish/initialState.js
src/components/createWish/modules/createWishPanel.js
src/components/createWish/modules/livePreviewPanel.js
src/components/createWish/pages/createWishPage.js
src/components/createWish/reducers.js
src/components/createWish/selectors.js
store.js

In this PR,
- Used `useReducer` with `useContext` to expose `state and dispatch` to all the components within `createWish`
Reason:
- There is no need for creating of wishes to be store in global store. 
- While there may be more boiler plate files, it is beneficial that we do not pollute the global store unnecessary

Remove redux from create-wish page

---

src/components/createDonation/context.js
src/components/createDonation/index.js
src/components/createDonation/initialState.js
src/components/createDonation/modules/createDonationPanel.js
src/components/createDonation/modules/livePreviewDonation.js
src/components/createDonation/pages/createDonationPage.js
src/components/createDonation/reducers.js
src/components/createDonation/selectors.js
store.js

In this PR,
- Used `useReducer` with `useContext` to expose `state and dispatch` to all the components within `createWish`
Reason:
- There is no need for creating of donation to be store in global store. 
- While there may be more boiler plate files, it is beneficial that we do not pollute the global store unnecessary

Remove redux from create-donation page

---

src/components/chat/modules/ListOfChats.js

The empty chat text container still shows even in mobile view, causing weird UI.

Add conditionally show when no chats available

---

pages/chat/index.js
pages/login.js
src/components/login/modules/LoginDonor.js
src/components/login/modules/LoginNpo.js
src/components/login/pages/LoginPage.js

```
Currently, when a not-logged-in user accesses a chat from a 
particular chat email, he/she will be redirected to an error page. 
Let's modify such that the user will first be redirected to the 
login page. After logging in, the user will be redirected back to
the originating chat page that he/she was supposed to be.
```

Redirect back to chat after login

---

pages/index.js
src/components/onboarding/Onboarding.js
src/components/register/modules/RegisterDonor.js
src/components/register/modules/RegisterNpoDetails.js
utils/constants/onboarding.js

In this PR,
- Added Onboarding modal UI for donor and NPO
- Accessible via `?next=onboarding`
Todo:

Add onboarding ui

---

src/components/partners/modules/PartnersContent.js

Issue:
Initial rendering - whole NVPC description is underlined instead of only the textlink tag

Fix weird render for partner page

---

src/components/home/modules/algoliaHelpers.js

In this PR,
- Fixed the wrong query for top wishes. But commented out currently because we are allowing expired wishes.

Fix wrong query (top wishes)

---

src/components/chat/modules/ChatDialogMessages.js

Recently chrome has a negative scrollTop with column-reverse when scrolling up, whereas previously only Safari has this issue.
This chrome update causes the scroll to bottom button not disappearing when it is at the bottom of the page.
Note that bottom position will always be zero. Hence,  adding the check that the scrollTop is not zero when setting the scroll to bottom to be visible, we will ensure that the button will not be visible when it is at the bottom of the page.

Chat: Fix chrome issue with negative scrollTop

---

src/components/navbar/modules/TopRightNavigation.js

- Utilised router.asPath instead of router.pathname as router.pathname returns the pathname i.e. `/wish/[wishId]` instead of `/wish/1234245789ryrjewfhbjksd`

Add redirect after login

---

package-lock.json
package.json

Add `husky` as dev dependency to run pre-commit hook that runs `npm run format`.
This ensures that `prettier` will always be ran before making a commit, which solves the problem of devs forgetting to run it.

Add husky pre-commit hook to run prettier

---

pages/search.js
src/components/navbar/modules/TopLeftNavigation.js
src/pages/search/components/MobileSearchBar/index.js
src/pages/search/components/NavSearchBar/components/SearchBarV2/index.js
src/pages/search/components/NavSearchBar/components/index.js
src/pages/search/components/NavSearchBar/index.js
src/pages/search/components/NavSearchBarDropdownList/components/AlgoliaSearchBar/index.js
src/pages/search/components/NavSearchBarDropdownList/components/Hits/index.js
src/pages/search/components/NavSearchBarDropdownList/components/index.js
src/pages/search/components/NavSearchBarDropdownList/index.js
src/pages/search/components/index.js
src/pages/search/index.js

Note: in the future, may need to move `NavSearchBar` into `src/components` since `TopLeftNavigation` uses it.

Refactor structure of search page
